name: snowflake-cicd-demo-liquibase

on:
  push:
    branches:
      - master
    paths:
      - 'changesets/**'
  workflow_dispatch:

jobs:
  deploy-changes-in-dev:
    runs-on: ubuntu-latest
    environment: ic/dev
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'

      - name: Set up Liquibase
        run: |
          wget -q https://github.com/liquibase/liquibase/releases/download/v4.5.0/liquibase-4.5.0.tar.gz
          tar xf liquibase-4.5.0.tar.gz
          rm liquibase-4.5.0.tar.gz
          chmod +x liquibase

      - name: Install Snowflake JDBC driver
        run: |
          wget -q https://repo1.maven.org/maven2/net/snowflake/snowflake-jdbc/3.13.8/snowflake-jdbc-3.13.8.jar
          
      - name: Apply database changes
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SF_USERNAME }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SF_PASSWORD }}
          SNOWFLAKE_DATABASE: ${{ secrets.SF_DATABASE }}
          SNOWFLAKE_SCHEMA: ${{ secrets.SF_SCHEMA }}
          SNOWFLAKE_ROLE: ${{ secrets.SF_ROLE }}
        run: |
          echo "Step 1: Checking Liquibase Version"
          ./liquibase --version
          echo "Step 2: Checking GitHub Workspace Directory"
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          echo "Step 3: Deploy DB Changes"
          


  deploy-changes-in-prod:
    runs-on: ubuntu-latest
    environment: ic/prod
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'

      - name: Set up Liquibase
        run: |
          wget -q https://github.com/liquibase/liquibase/releases/download/v4.5.0/liquibase-4.5.0.tar.gz
          tar xf liquibase-4.5.0.tar.gz
          rm liquibase-4.5.0.tar.gz
          chmod +x liquibase

      - name: Install Snowflake JDBC driver
        run: |
          wget -q https://repo1.maven.org/maven2/net/snowflake/snowflake-jdbc/3.13.8/snowflake-jdbc-3.13.8.jar
          mv snowflake-jdbc-3.13.8.jar liquibase/lib/

      - name: Apply database changes
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SF_USERNAME }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SF_PASSWORD }}
          SNOWFLAKE_DATABASE: ${{ secrets.SF_DATABASE }}
          SNOWFLAKE_SCHEMA: ${{ secrets.SF_SCHEMA }}
          SNOWFLAKE_ROLE: ${{ secrets.SF_ROLE }}
        run: |
          ./liquibase --version

